### ISSUE TITLE
searxng not working on local network

### ISSUE THREAD

**Issue by SomeHybrid** [searxng/searxng-docker#105]
I am trying to install searxng-docker on my Raspberry Pi 4 on my local network, however nothing happens when I go to searxng's docker port.

The files except for the settings.yml file have been unchanged, and I have added the key to the settings.yml file.

Logs: https://pastebin.com/30FRDknj

**Comment by luckkmaxx** [comment]
Hi, your logs says:
*** WARNING: Can't find section "uwsgi" in INI configuration file /etc/searxng/uwsgi.ini ***

Maybe you deleted some text by mistake in uwsgi.ini file. It should have
```
[uwsgi]
# Who will run the code
uid = searxng
gid = searxng
```
at the very begining.
Can you check this?
There are also other warnings in log, but maybe the cause is due to this too.

**Comment by return42** [comment]
closed due to lack of feedback
