### ISSUE TITLE
cp: can't create '/etc/searxng/uwsgi.ini': Permission denied

### ISSUE THREAD

**Issue by Onur-Cansever** [searxng/searxng-docker#115]
I followed the README.md.

output of docker compose up:

searxng  | SearXNG version 2023.01.20+316fcd5e
searxng  | Create /etc/searxng/uwsgi.ini
searxng  | cp: can't create '/etc/searxng/uwsgi.ini': Permission denied
searxng  | sed: /etc/searxng/uwsgi.ini: No such file or directory
searxng  | Use existing /etc/searxng/settings.yml
searxng  | Listen on 0.0.0.0:8080
searxng  | realpath() of /etc/searxng/uwsgi.ini failed: No such file or directory [core/utils.c line 3662]
searxng exited with code 1

What can i do about it?

UPDATE: I just run commands with superuser permissions, It fixed.

**Comment by LucianoRicardo737** [comment]
I have the same problem. could you fix it?

**Comment by LucianoRicardo737** [comment]
> I have the same problem. could you fix it?

Done. Create uwsgi.ini file inside of /searxng-docker/searxng. The problem is this file, dont exist in searxng folder. 

Here the file:

`
[uwsgi]
# Who will run the code
uid = searxng
gid = searxng

# Number of workers (usually CPU count)
workers = %k
threads = 4

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpreter config
single-interpreter = true
master = true
plugin = python3
lazy-apps = true
enable-threads = 4

# Module to import
module = searx.webapp

# Virtualenv and python path
pythonpath = /usr/local/searxng/
chdir = /usr/local/searxng/searx/

# automatically set processes name to something meaningful
auto-procname = true

# Disable request logging for privacy
disable-logging = true
log-5xx = true

# Set the max size of a request (request-body excluded)
buffer-size = 8192

# No keep alive
# See https://github.com/searx/searx-docker/issues/24
add-header = Connection: close

# uwsgi serves the static files
# expires set to one year since there are hashes
static-map = /static=/usr/local/searxng/searx/static
static-expires = /* 31557600
static-gzip-all = True
offload-threads = 4

# Cache
cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
`

**Comment by HeyMika** [comment]
Can confirm this works. Just create the uwsgi.ini inside /searxng-docker/searxng and redeploy the container again. Thanks!

**Comment by qrhfz** [comment]
that file should be in repository

**Comment by jerem0808** [comment]
Hi 
why this issue is fixed?
https://github.com/searxng/searxng-docker/tree/master/searxng
The repository still doesn't contain this file.

**Comment by codeDude64** [comment]
> > I have the same problem. could you fix it?
> 
> Done. Create uwsgi.ini file inside of /searxng-docker/searxng. The problem is this file, dont exist in searxng folder.
> 
> Here the file:
> 
> ```
> 
> [uwsgi]
> # Who will run the code
> uid = searxng
> gid = searxng
> 
> # Number of workers (usually CPU count)
> workers = %k
> threads = 4
> 
> # The right granted on the created socket
> chmod-socket = 666
> 
> # Plugin to use and interpreter config
> single-interpreter = true
> master = true
> plugin = python3
> lazy-apps = true
> enable-threads = 4
> 
> # Module to import
> module = searx.webapp
> 
> # Virtualenv and python path
> pythonpath = /usr/local/searxng/
> chdir = /usr/local/searxng/searx/
> 
> # automatically set processes name to something meaningful
> auto-procname = true
> 
> # Disable request logging for privacy
> disable-logging = true
> log-5xx = true
> 
> # Set the max size of a request (request-body excluded)
> buffer-size = 8192
> 
> # No keep alive
> # See https://github.com/searx/searx-docker/issues/24
> add-header = Connection: close
> 
> # uwsgi serves the static files
> # expires set to one year since there are hashes
> static-map = /static=/usr/local/searxng/searx/static
> static-expires = /* 31557600
> static-gzip-all = True
> offload-threads = 4
> 
> # Cache
> cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
> ```

Where did you get this file?

**Comment by return42** [comment]
I'm not a docker user, but what I can say: Its already in the docker image

- https://github.com/searxng/searxng/blob/799d72e3fd74fd0967a79f07bbf541ce7f0f3e84/dockerfiles/docker-entrypoint.sh#L62-L70

- https://github.com/searxng/searxng/blob/master/dockerfiles/uwsgi.ini

----

> output of docker compose up:
> ...
> searxng | cp: can't create '/etc/searxng/uwsgi.ini': Permission denied

'/etc/searxng/uwsgi.ini' isn't created since "Permission denied"

> searxng | sed: /etc/searxng/uwsgi.ini: No such file or directory
> searxng | sed: /etc/searxng/uwsgi.ini: No such file or directory
> searxng | realpath() of /etc/searxng/uwsgi.ini failed: No such file or directory [core/utils.c line 3662]

.. are follow up issues .. and the OP says:

> UPDATE: I just run commands with superuser permissions, It fixed.

**Comment by ppfeufer** [comment]
See the discussion in this PR » https://github.com/searxng/searxng-docker/pull/238

**Comment by DanielBoettner** [comment]
Just for reference, it is mentioned in the README.md

> [!NOTE]
On the first run, you must remove cap_drop: - ALL from the docker-compose.yaml file for the searxng service to successfully create **/etc/searxng/uwsgi.ini**. This is necessary because the cap_drop: - ALL directive removes all capabilities, including those required for the creation of the uwsgi.ini file. After the first run, you should re-add cap_drop: - ALL to the docker-compose.yaml file for security reasons.

I did not set it first.
But doing so works as intended. 

I short

Change 
```yml
    cap_drop:
      - ALL
```
to 
```yml
#    cap_drop:
#      - ALL
```

* execute `docker compose up -d` 
* change the above back 
* execute `docker compose up -d --force-recreate`

**Comment by martinjgrunwald** [comment]
I got the error again after updating to 2025.5.20. Reverting back to 2025.5.18

**Comment by unixfox** [comment]
https://github.com/searxng/searxng/issues/4806
