### ISSUE TITLE
Any way to extend the certificate timeout

### ISSUE THREAD

**Issue by diiirt** [searxng/searxng-docker#35]
I really like searxng and it is working great for me.  I have one issue though,  after ~6hrs or so I have to again accept the self signed cert in my web browser.   I have no intention to make this forward facing or accessible outside my lan.  Is there some way to work around this issue.   Keep up the great work!

**Comment by mrpaulblack** [comment]
Hi @diiirt ,
This does not sound like a SearXNG problem to me but rather as a browser feature. Your browser does only allow a exception rule for self singed certs for 12 hours. If you plan to use the instance only on your lan you could set caddy to only do HTTP -> you can look up a solution on the caddy docs for that; Here are the docs: https://caddyserver.com/docs/ and I think this could help you if you dont find it in the docs: https://caddyserver.com/docs/automatic-https


Another way could be to add the local CA (certificate authority) to your browser. Meaning: Your browser will accept all HTTP connections to your local SearXNG instance as valid and will show a green lock next to your instance -> You would need to set this up on any device that uses SearXNG. About where the CA for caddy is located here: https://caddyserver.com/docs/automatic-https
Here is a starting point on how to add a root CA to your browser: https://paulgo.io/search?q=browser%20add%20root%20CA&language=en-US&time_range=None&safesearch=1&categories=general

I will close this since its IMO not really a SearXNG problem. If you have more questions or found a solution please put them here as a comment for others to find :+1: ; Closing.

**Comment by diiirt** [comment]
> 

Thanks, I was able to add the root crt to my system.  I found it following your link. It's in:
/caddy-data/caddy/pki/authorities/local/root.crt

P.S.  There is something different about how caddy works.  I don't know enough to speak intelligently about it but for all the other local servers I create I can just accept the cert in the browser and I don't need to accept it again.  Maybe it's the way the reverse proxy works but it's almost as if the cert I am accepting is not the real cert.   Adding the root crt worked though.
