### ISSUE TITLE
Can I make user in Searxng??

### ISSUE THREAD

**Issue by Mostafaibsharaf019** [searxng/searxng-docker#80]
### _**How Can I make user in Searxng??**_

**Comment by return42** [comment]
Can you please stop open issues for trivial questions otherwise we have to  block your account .. and it won't help to wrote bold face.

Given that SearXNG is made to protect privacy and not to track its user, you can answer your question by yourself.

You can ask your questions at [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org)
